FlouVideoWidgetBundle:
    resource: "@FlouVideoWidgetBundle/Resources/config/routing.yml"
    prefix:   /

FlouVideoAssetBundle:
    resource: "@FlouVideoAssetBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_flou_videomanagerbundle:
    resource: "@FlouVideoManagerBundle/Resources/config/routing.yml"


