security:

    encoders:
            FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER, ROLE_ALLOWED_TO_SWITCH
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:

        secured_area:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: user_info
            logout: true
            anonymous: true
            switch_user: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/channel/, role: ROLE_USER }
        - { path: ^/page/, role: ROLE_USER }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/video/, role: ROLE_USER }
        - { path: ^/widget/, role: ROLE_USER }
        - { path: ^/playlist/, role: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
