<?php

namespace Flou\VideoManagerBundle\Repository;

use Flou\VideoManagerBundle\Entity\Page;

use Doctrine\ORM\EntityRepository;
/**
 * DesignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class AbstractWidgetRepository extends EntityRepository
{
	public function findListByChannelId($channelid, $pageid=0, $language= 'de')
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT	widget,
				t.title_'.$language.' as title,
				'.$this->getAdditionalSelect().'
				pos.id as position
				FROM '.$this->getNamespace().' widget
				JOIN widget.title t
				JOIN widget.position pos
				'.$this->getAdditionalJoin().' 
				JOIN widget.channel c WHERE c.id = :id AND ('.
									'(widget.page = :pid AND widget.showonpage = true) OR '.
									'('.Page::ALL.' = :pid) OR '.
									'(widget.page is NULL AND widget.showonpage = true) OR '.
									'(widget.showonvideo = true AND :pid = '.Page::VIDEO.')'.
									')'
		)->setParameter('id', $channelid)->setParameter('pid', $pageid);
		
		return ($query->getResult());
	}
	
	protected abstract function getNamespace();
	
	/// USED TO AVOID LAZY LOADING
	protected function getAdditionalJoin(){
		return '';
	}
	
	protected function getAdditionalSelect(){
		return '';
	}
	////
	
	public static function generateEndString(){
		return 'WHERE c.id = :id AND ('.
									'(widget.page = :pid AND widget.showonpage = true) OR '.
									'('.Page::ALL.' = :pid) OR '.
									'(widget.page is NULL AND widget.showonpage = true) OR '.
									'(widget.showonvideo = true AND :pid = '.Page::VIDEO.')'.
									')';
	}
}