<?php

namespace Flou\VideoManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends EntityRepository
{
	public function findUnitedFirstByChannelId($id)
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT	c.id,
				c.channelname,
				c.language_de,
				c.language_en,
				c.language_fr,
				c.use_html5,
				c.piwikid,
				c.fbid,
				c.use_hyphernate
				FROM FlouVideoManagerBundle:Channel c
				WHERE c.id = :id'
		)->setParameter('id', $id);
	
		return ($query->getSingleResult());
	}
}