<?php

namespace Flou\VideoManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DesignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignRepository extends EntityRepository
{
	public function findUnitedFirstByChannelId($id)
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT	d.id,
				d.color1,
				d.color2,
				d.color3,
				d.hovercolor1,
				d.hovercolor2,
				d.hovercolor3,
				d.fontcolor1,
				d.fontcolor2,
				d.fontcolor3,
				d.hoverfontcolor1,
				d.hoverfontcolor2,
				d.hoverfontcolor3,
				d.linkcolor1,
				d.linkcolor2,
				d.linkcolor3,
				d.hoverlinkcolor1,
				d.hoverlinkcolor2,
				d.hoverlinkcolor3,
				d.head,
				t.id as template,
				f.name as font,
				d.headingcolor,
				hf.name as headingfont
				
				
				FROM FlouVideoManagerBundle:Design d
				JOIN d.font f
				JOIN d.headingfont hf
				JOIN d.channel c
				JOIN d.template t
				WHERE c.id = :id'
		)->setParameter('id', $id);
	
		return ($query->getSingleResult());
	}
}