<?php

namespace Flou\VideoManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DesignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends EntityRepository
{
	public function findListByDomain($domain)
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT d
				FROM FlouVideoManagerBundle:Domain d
				WHERE d.name = :domain'
		)->setParameter('domain', $domain);
	
		return ($query->getSingleResult());
	}
	
	public function findHostbyChannelId($channel)
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT d.name
				FROM FlouVideoManagerBundle:Domain d
				JOIN d.channel c
				WHERE c.id = :channel'
		)->setParameter('channel', $channel);
	
		return ($query->getResult());
	}
}