<?php

namespace Flou\VideoManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
	public function findUnitedFirstByGalleryId($id, $language = 'de')
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT g.id,
				t.title_'.$language.' as title
				FROM FlouVideoManagerBundle:Gallery g
				JOIN g.title t
				WHERE g.id = :id'
		)->setParameter('id', $id);
	
		return ($query->getSingleResult());
	}
}