<?php

namespace Flou\VideoManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
	public function findUnitedListByChannelId($id, $language = 'de')
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT p.id,
				pos.id as position,
				p.hyperlink,
				g.title_'.$language.' as menugroup,
				t.title_'.$language.' as title

				FROM FlouVideoManagerBundle:Page p
				JOIN p.title t
				JOIN p.group g
				JOIN p.channel c
				JOIN p.pageposition pos
				WHERE c.id = :id
				AND t.title_'.$language.' <> \'\'
				AND pos <> 0
				ORDER BY p.orderrank ASC'
		)->setParameter('id', $id);
	
		return ($query->getResult());
	}
	
	public function findUnitedFirstById($id, $language = 'de')
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT p.id,
				c.id as channel,
				t.title_'.$language.' as title,
				d.description_'.$language.' as description
				FROM FlouVideoManagerBundle:Page p
				JOIN p.title t
				JOIN p.channel c
				JOIN p.description d
				WHERE p.id = :id'
		)->setParameter('id', $id);
	
		return ($query->getSingleResult());
	}
}