<?php

namespace Flou\VideoManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
	public function findUnitedListByGalleryId($id, $language = 'de')
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT	p.id,
				t.title_'.$language.' as title
				FROM FlouVideoManagerBundle:Photo p
				JOIN p.gallery g
				JOIN p.title t
				WHERE g.id = :id
				ORDER BY p.orderrank ASC'
		)->setParameter('id', $id);
	
		return ($query->getResult());
	}
	
	public function findUnitedFirstById($id, $language = 'de')
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT	p.id,
				t.title_'.$language.' as title,
				g.id as gallery,
				d.description_'.$language.' as description
				FROM FlouVideoManagerBundle:Photo p
				JOIN p.title t
				JOIN p.description d
				JOIN p.gallery g
				WHERE p.id = :id
				ORDER BY p.orderrank ASC'
		)->setParameter('id', $id);
	
		return ($query->getSingleResult());
	}
}