<?php

namespace Flou\VideoManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * DesignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextWidgetRepository extends AbstractWidgetRepository
{
	public function findUnitedListByChannelId($id,  $language = 'de')
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT	tw.id,
				pos.id as position,
				t.title_'.$language.' as title,
				d.description_'.$language.' as description,
				tw.orderrank as rank				
				FROM FlouVideoManagerBundle:TextWidget tw
				JOIN tw.title t
				JOIN tw.pageposition pos
				JOIN tw.description d
				JOIN tw.channel c
				WHERE c.id = :id'
		)->setParameter('id', $id);
	
		return ($query->getResult());
	}
	
	public function findListByChannelId($id)
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT	tw
				FROM FlouVideoManagerBundle:TextWidget tw
				JOIN tw.channel c
				WHERE c.id = :id'
		)->setParameter('id', $id);
	
		return ($query->getResult());
	}
}