<?php

namespace Flou\VideoManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
	public function findUnitedListByChannelId($id, $language = 'de')
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT	v.id,
						v.uploadtime as date,
						v.duration,
						v.http,
						sd.description_'.$language.' as shortdescription,
						t.title_'.$language.' as title
				FROM FlouVideoManagerBundle:Video v
				JOIN v.title t
				JOIN v.shortdescription sd
				WHERE v.channel = :id
				AND v.enabled = true
				AND t.title_'.$language.' <> \'\''
		)->setParameter('id', $id);
		
		return ($query->getResult());
	}
	
	public function findUnitedPlayinfoListByChannelId($id, $language = 'de')
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT	v.id,
				'.$id.' as channel,
				v.uploadtime as date,
				v.duration,
				v.http,
				v.rtmp,
				v.s3key,
				t.title_'.$language.' as title
				FROM FlouVideoManagerBundle:Video v
				JOIN v.title t
				WHERE v.channel = :id
				AND v.enabled = true
				AND t.title_'.$language.' <> \'\''
		)->setParameter('id', $id);
	
		return ($query->getResult());
	}
	
	public function findUnitedFirstById($id, $language = 'de')
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT	v.id,
				v.uploadtime as date,
				v.duration,
				v.http,
				c.id as channel,
				d.description_'.$language.' as description,
				sd.description_'.$language.' as shortdescription,
				t.title_'.$language.' as title
				FROM FlouVideoManagerBundle:Video v
				JOIN v.title t
				JOIN v.description d
				JOIN v.channel c
				JOIN v.shortdescription sd
				WHERE v.id = :id'
		)->setParameter('id', $id);
	
		return ($query->getSingleResult());
	}
	
	public function findUnitedPlayinfoFirstById($id, $language = 'de')
	{
		$query = $this->getEntityManager()
		->createQuery('
				SELECT	v.id,
				v.duration,
				v.http,
				v.rtmp,
				v.s3key,
				c.id as channel,
				t.title_'.$language.' as title
				FROM FlouVideoManagerBundle:Video v
				JOIN v.title t
				JOIN v.channel c
				WHERE v.id = :id'
		)->setParameter('id', $id);
	
		return ($query->getSingleResult());
	}
}